site_name: tacl2025_ood_eval_self_rationalization
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: tacl2025_ood_eval_self_rationalization
      handlers:
        python:
          options:
            docstring_style: numpy